schema:
  tables:
    customer_credit:
      columns:
        customer_id: 
          type: "integer"
          description: "Unique identifier for customer"
        credit_score:
          type: "integer"
          description: "Credit score between 300-850"
          synonyms: ["fico score", "fico", "credit rating"]
        risk_rating:
          type: "string"
          description: "Risk classification"
          allowed_values: ["LOW", "MEDIUM", "HIGH"]
      relationships:
        - table: "payment_history"
          type: "one_to_many"
          join_conditions:
            - "customer_credit.customer_id = payment_history.customer_id"
    
    payment_history:
      columns:
        payment_id:
          type: "integer"
          description: "Unique identifier for payment"
        customer_id:
          type: "integer"
          description: "Unique identifier for customer"
        payment_date:
          type: "date"
          description: "Date of the payment"
        payment_amount:
          type: "decimal"
          description: "Amount of the payment"
        payment_status:
          type: "string"
          description: "Status of the payment"
          allowed_values: ["Paid", "Pending", "Late"]
      relationships:
        - table: "customer_credit"
          type: "many_to_one"
          join_conditions:
            - "payment_history.customer_id = customer_credit.customer_id"

domain_terms:
  - term: "fico score"
    description: "Credit score ranging from 300-850"
    table: "customer_credit"
    column: "credit_score"
    synonyms: ["fico", "credit rating", "credit worthiness"]
    
  - term: "late payment"
    description: "Payment made after the due date"
    table: "payment_history"
    column: "payment_status"
    value: "Late"
    synonyms: ["overdue payment", "delayed payment"]
    
  - term: "credit risk"
    description: "Level of risk associated with a customer"
    table: "customer_credit"
    column: "risk_rating"
    synonyms: ["risk level", "risk score"]

business_rules:
  - name: "credit_score_range"
    condition: "credit_score BETWEEN 300 AND 850"
    error_message: "Credit score must be between 300 and 850"
  - name: "risk_rating_values"
    condition: "risk_rating IN ('LOW', 'MEDIUM', 'HIGH')"
    error_message: "Invalid risk rating value" 